sudo: true
language: node_js
node_js:
  - "9"
script:
  - npm t
  - npm run build
deploy:
  skip_cleanup: true
  - provider: script
    script: ./travis-ci-deploy.sh production
    on:
      branch: master
  - provider: script
    script: ./travis-ci-deploy.sh staging
    on:
      branch: staging
